name: dockerimagetransfer

on:
  push:
    branches: [ "main" ]

# Environment variables available to all jobs and steps in this workflow.
env:
  source_registry_username: 
  destination_registry_username: confucian_tju@hotmail.com
  source_registry_password: 
  destination_registry_password: Li69nux*1234
  destination_registry: registry.cn-hangzhou.aliyuncs.com
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    
    services:
      registry:
        image: registry:2
        ports:
          - 5001:5000
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Transfer Docker image 
        uses: alvinyangrs/docker-image-transfer-action@main # alex289/docker-image-transfer-action@v1.2.1
        with:
          source: 'node:lts-alpine'
          destination: 'registry.cn-hangzhou.aliyuncs.com/ryang-test/test:lts-alpine1'


